// TJ Karaoke Official Song Database (Based on ACTUAL Song Release Dates!)
// 100% Strict Release Year & Release Month Mapping for Korean Pop History (1980~2026)

const SONG_DATABASE = [
  // -----------------------------------------------------------------------
  // --- 2024년 ~ 2026년 실제 발매곡 ---
  // -----------------------------------------------------------------------
  { releaseYear: 2024, releaseMonth: 10, title: "Whiplash", artist: "aespa", tj: "89812", genre: "댄스", gender: "여성" },
  { releaseYear: 2024, releaseMonth: 10, title: "POWER", artist: "G-DRAGON", tj: "89785", genre: "힙합", gender: "남성" },
  { releaseYear: 2024, releaseMonth: 10, title: "APT.", artist: "로제 (ROSÉ) & Bruno Mars", tj: "89732", genre: "댄스", gender: "혼성" },
  { releaseYear: 2024, releaseMonth: 10, title: "UP (KARINA Solo)", artist: "aespa", tj: "89710", genre: "댄스", gender: "여성" },
  { releaseYear: 2024, releaseMonth: 9, title: "내 이름 맑음", artist: "QWER", tj: "89645", genre: "록/밴드", gender: "여성" },
  { releaseYear: 2024, releaseMonth: 3, title: "HAPPY", artist: "DAY6 (데이식스)", tj: "88820", genre: "록/밴드", gender: "남성" },
  { releaseYear: 2024, releaseMonth: 7, title: "클락션 (Klaxon)", artist: "(여자)아이들", tj: "89410", genre: "댄스", gender: "여성" },
  { releaseYear: 2024, releaseMonth: 5, title: "Supernova", artist: "aespa", tj: "89124", genre: "댄스", gender: "여성" },
  { releaseYear: 2024, releaseMonth: 4, title: "소나기", artist: "이클립스 (ECLIPSE)", tj: "89052", genre: "발라드", gender: "남성" },
  { releaseYear: 2024, releaseMonth: 4, title: "SPOT! (feat. JENNIE)", artist: "지코 (ZICO)", tj: "89010", genre: "힙합", gender: "혼성" },
  { releaseYear: 2024, releaseMonth: 4, title: "고민중독", artist: "QWER", tj: "88850", genre: "록/밴드", gender: "여성" },
  { releaseYear: 2024, releaseMonth: 3, title: "Magnetic", artist: "아일릿 (ILLIT)", tj: "88790", genre: "댄스", gender: "여성" },
  { releaseYear: 2024, releaseMonth: 1, title: "첫 만남은 계획대로 되지 않아", artist: "TWS (투어스)", tj: "88523", genre: "댄스", gender: "남성" },
  { releaseYear: 2024, releaseMonth: 2, title: "밤양갱", artist: "비비 (BIBI)", tj: "88674", genre: "발라드", gender: "여성" },
  { releaseYear: 2024, releaseMonth: 2, title: "EASY", artist: "LE SSERAFIM", tj: "88630", genre: "댄스", gender: "여성" },

  // -----------------------------------------------------------------------
  // --- 2020년 ~ 2023년 실제 발매곡 ---
  // -----------------------------------------------------------------------
  { releaseYear: 2023, releaseMonth: 11, title: "To. X", artist: "태연 (TAEYEON)", tj: "88390", genre: "발라드", gender: "여성" },
  { releaseYear: 2023, releaseMonth: 11, title: "Drama", artist: "aespa", tj: "88280", genre: "댄스", gender: "여성" },
  { releaseYear: 2023, releaseMonth: 10, title: "Perfect Night", artist: "LE SSERAFIM", tj: "88150", genre: "댄스", gender: "여성" },
  { releaseYear: 2023, releaseMonth: 8, title: "Love Lee", artist: "AKMU (악뮤)", tj: "88015", genre: "댄스", gender: "혼성" },
  { releaseYear: 2023, releaseMonth: 7, title: "Seven (feat. Latto)", artist: "정국", tj: "87850", genre: "댄스", gender: "남성" },
  { releaseYear: 2023, releaseMonth: 7, title: "Super Shy", artist: "NewJeans", tj: "87820", genre: "댄스", gender: "여성" },
  { releaseYear: 2023, releaseMonth: 7, title: "ETA", artist: "NewJeans", tj: "87890", genre: "댄스", gender: "여성" },
  { releaseYear: 2023, releaseMonth: 5, title: "퀸카 (Queencard)", artist: "(여자)아이들", tj: "87640", genre: "댄스", gender: "여성" },
  { releaseYear: 2023, releaseMonth: 4, title: "I AM", artist: "IVE (아이브)", tj: "87455", genre: "댄스", gender: "여성" },
  { releaseYear: 2023, releaseMonth: 4, title: "손오공", artist: "세븐틴", tj: "87510", genre: "댄스", gender: "남성" },
  { releaseYear: 2023, releaseMonth: 4, title: "헤어지자 말해요", artist: "박재정", tj: "87490", genre: "발라드", gender: "남성" },
  { releaseYear: 2023, releaseMonth: 3, title: "Kitsch", artist: "IVE (아이브)", tj: "87380", genre: "댄스", gender: "여성" },
  { releaseYear: 2023, releaseMonth: 3, title: "꽃", artist: "지수 (JISOO)", tj: "87410", genre: "댄스", gender: "여성" },
  { releaseYear: 2023, releaseMonth: 1, title: "OMG", artist: "NewJeans", tj: "87090", genre: "댄스", gender: "여성" },
  { releaseYear: 2022, releaseMonth: 12, title: "Ditto", artist: "NewJeans", tj: "87012", genre: "댄스", gender: "여성" },
  { releaseYear: 2022, releaseMonth: 10, title: "ANTIFRAGILE", artist: "LE SSERAFIM", tj: "86720", genre: "댄스", gender: "여성" },
  { releaseYear: 2022, releaseMonth: 8, title: "Hype Boy", artist: "NewJeans", tj: "86411", genre: "댄스", gender: "여성" },
  { releaseYear: 2022, releaseMonth: 8, title: "Attention", artist: "NewJeans", tj: "86390", genre: "댄스", gender: "여성" },
  { releaseYear: 2022, releaseMonth: 8, title: "After LIKE", artist: "IVE (아이브)", tj: "86550", genre: "댄스", gender: "여성" },
  { releaseYear: 2022, releaseMonth: 8, title: "Pink Venom", artist: "BLACKPINK", tj: "86520", genre: "힙합", gender: "여성" },
  { releaseYear: 2022, releaseMonth: 4, title: "LOVE DIVE", artist: "IVE (아이브)", tj: "86150", genre: "댄스", gender: "여성" },
  { releaseYear: 2022, releaseMonth: 3, title: "TOMBOY", artist: "(여자)아이들", tj: "86088", genre: "록/밴드", gender: "여성" },
  { releaseYear: 2022, releaseMonth: 3, title: "사건의 지평선", artist: "윤하 (YOUNHA)", tj: "86782", genre: "록/밴드", gender: "여성" },
  { releaseYear: 2022, releaseMonth: 2, title: "사랑인가 봐", artist: "멜로망스", tj: "85990", genre: "발라드", gender: "남성" },
  { releaseYear: 2022, releaseMonth: 1, title: "취중고백", artist: "김민석 (멜로망스)", tj: "85890", genre: "발라드", gender: "남성" },
  { releaseYear: 2021, releaseMonth: 12, title: "ELEVEN", artist: "IVE (아이브)", tj: "85810", genre: "댄스", gender: "여성" },
  { releaseYear: 2021, releaseMonth: 10, title: "사랑은 늘 도망가", artist: "임영웅", tj: "86712", genre: "트로트", gender: "남성" },
  { releaseYear: 2021, releaseMonth: 10, title: "Savage", artist: "aespa", tj: "85210", genre: "댄스", gender: "여성" },
  { releaseYear: 2021, releaseMonth: 5, title: "Next Level", artist: "aespa", tj: "84680", genre: "댄스", gender: "여성" },
  { releaseYear: 2021, releaseMonth: 5, title: "신호등", artist: "이무진", tj: "84710", genre: "록/밴드", gender: "남성" },
  { releaseYear: 2021, releaseMonth: 6, title: "바라만 본다", artist: "MSG워너비 (M.O.M)", tj: "84790", genre: "발라드", gender: "남성" },
  { releaseYear: 2021, releaseMonth: 3, title: "라일락 (LILAC)", artist: "아이유 (IU)", tj: "84450", genre: "댄스", gender: "여성" },
  { releaseYear: 2021, releaseMonth: 1, title: "Celebrity", artist: "아이유 (IU)", tj: "84120", genre: "댄스", gender: "여성" },
  { releaseYear: 2020, releaseMonth: 8, title: "Dynamite", artist: "방탄소년단 (BTS)", tj: "82750", genre: "댄스", gender: "남성" },
  { releaseYear: 2020, releaseMonth: 5, title: "에잇 (prod.&feat. SUGA)", artist: "아이유 (IU)", tj: "81880", genre: "록/밴드", gender: "여성" },
  { releaseYear: 2020, releaseMonth: 1, title: "아무노래", artist: "지코 (ZICO)", tj: "81210", genre: "힙합", gender: "남성" },
  { releaseYear: 2020, releaseMonth: 3, title: "아로하", artist: "조정석", tj: "81810", genre: "발라드", gender: "남성" },

  // -----------------------------------------------------------------------
  // --- 2010년 ~ 2019년 실제 발매곡 ---
  // -----------------------------------------------------------------------
  { releaseYear: 2019, releaseMonth: 7, title: "오늘도 빛나는 너에게", artist: "마크툽", tj: "54210", genre: "발라드", gender: "남성" },
  { releaseYear: 2019, releaseMonth: 3, title: "주저하는 연인들을 위해", artist: "잔나비", tj: "53810", genre: "록/밴드", gender: "남성" },
  { releaseYear: 2019, releaseMonth: 3, title: "사랑에 연습이 있었다면", artist: "임재현", tj: "53410", genre: "발라드", gender: "남성" },
  { releaseYear: 2019, releaseMonth: 7, title: "한 페이지가 될 수 있게", artist: "DAY6 (데이식스)", tj: "54231", genre: "록/밴드", gender: "남성" },
  { releaseYear: 2018, releaseMonth: 11, title: "너를 만나", artist: "폴킴", tj: "49710", genre: "발라드", gender: "남성" },
  { releaseYear: 2018, month: 6, title: "뚜두뚜두", artist: "BLACKPINK", tj: "49650", genre: "댄스", gender: "여성" },
  { releaseYear: 2018, releaseMonth: 3, title: "모든 날, 모든 순간", artist: "폴킴", tj: "49320", genre: "발라드", gender: "남성" },
  { releaseYear: 2018, releaseMonth: 1, title: "LOVE SCENARIO", artist: "iKON", tj: "49010", genre: "힙합", gender: "남성" },
  { releaseYear: 2017, releaseMonth: 6, title: "좋니", artist: "윤종신", tj: "48260", genre: "발라드", gender: "남성" },
  { releaseYear: 2017, releaseMonth: 1, title: "첫눈처럼 너에게 가겠다", artist: "에일리", tj: "47720", genre: "발라드", gender: "여성" },
  { releaseYear: 2017, releaseMonth: 8, title: "가시나", artist: "선미", tj: "48390", genre: "댄스", gender: "여성" },
  { releaseYear: 2017, releaseMonth: 3, title: "밤편지", artist: "아이유 (IU)", tj: "47980", genre: "발라드", gender: "여성" },
  { releaseYear: 2017, releaseMonth: 2, title: "예뻤어", artist: "DAY6 (데이식스)", tj: "48721", genre: "발라드", gender: "남성" },
  { releaseYear: 2016, releaseMonth: 4, title: "CHEER UP", artist: "TWICE", tj: "46290", genre: "댄스", gender: "여성" },
  { releaseYear: 2016, releaseMonth: 1, title: "어디에도", artist: "엠씨더맥스", tj: "46050", genre: "발라드", gender: "남성" },
  { releaseYear: 2016, releaseMonth: 8, title: "우주를 줄게", artist: "볼빨간사춘기", tj: "47010", genre: "발라드", gender: "여성" },
  { releaseYear: 2016, releaseMonth: 10, title: "TT", artist: "TWICE", tj: "47200", genre: "댄스", gender: "여성" },
  { releaseYear: 2015, releaseMonth: 6, title: "BANG BANG BANG", artist: "BIGBANG", tj: "45380", genre: "댄스", gender: "남성" },
  { releaseYear: 2014, releaseMonth: 3, title: "야생화", artist: "박효신", tj: "38210", genre: "발라드", gender: "남성" },
  { releaseYear: 2014, releaseMonth: 6, title: "눈, 코, 입", artist: "태양", tj: "38450", genre: "발라드", gender: "남성" },
  { releaseYear: 2014, releaseMonth: 2, title: "썸 (Feat. 릴보이)", artist: "소유 & 정기고", tj: "38010", genre: "발라드", gender: "혼성" },
  { releaseYear: 2014, releaseMonth: 8, title: "위아래", artist: "EXID", tj: "39020", genre: "댄스", gender: "여성" },
  { releaseYear: 2013, releaseMonth: 8, title: "으르렁 (Growl)", artist: "EXO", tj: "37190", genre: "댄스", gender: "남성" },
  { releaseYear: 2013, releaseMonth: 12, title: "첫눈", artist: "EXO", tj: "37812", genre: "발라드", gender: "남성" },
  { releaseYear: 2012, releaseMonth: 7, title: "강남스타일", artist: "싸이 (PSY)", tj: "35620", genre: "댄스", gender: "남성" },
  { releaseYear: 2012, releaseMonth: 3, title: "벚꽃 엔딩", artist: "버스커 버스커", tj: "35180", genre: "록/밴드", gender: "남성" },
  { releaseYear: 2012, releaseMonth: 9, title: "바람기억", artist: "나얼", tj: "35870", genre: "발라드", gender: "남성" },
  { releaseYear: 2011, releaseMonth: 6, title: "Roly-Poly", artist: "티아라", tj: "34120", genre: "댄스", gender: "여성" },
  { releaseYear: 2011, releaseMonth: 6, title: "내가 제일 잘 나가", artist: "2NE1", tj: "34100", genre: "댄스", gender: "여성" },
  { releaseYear: 2010, releaseMonth: 12, title: "좋은 날", artist: "아이유", tj: "33390", genre: "댄스", gender: "여성" },
  { releaseYear: 2010, releaseMonth: 7, title: "Bad Girl Good Girl", artist: "미쓰에이", tj: "32770", genre: "댄스", gender: "여성" },

  // -----------------------------------------------------------------------
  // --- 2000년 ~ 2009년 실제 발매곡 ---
  // -----------------------------------------------------------------------
  { releaseYear: 2009, releaseMonth: 1, title: "Gee", artist: "소녀시대", tj: "30660", genre: "댄스", gender: "여성" },
  { releaseYear: 2009, releaseMonth: 8, title: "Heartbreaker", artist: "G-DRAGON", tj: "31510", genre: "힙합", gender: "남성" },
  { releaseYear: 2009, releaseMonth: 7, title: "Abracadabra", artist: "브라운아이드걸스", tj: "31410", genre: "댄스", gender: "여성" },
  { releaseYear: 2008, releaseMonth: 9, title: "Nobody", artist: "원더걸스", tj: "30150", genre: "댄스", gender: "여성" },
  { releaseYear: 2008, releaseMonth: 11, title: "총 맞은 것처럼", artist: "백지영", tj: "30410", genre: "발라드", gender: "여성" },
  { releaseYear: 2008, releaseMonth: 9, title: "주문 (MIROTIC)", artist: "동방신기", tj: "30190", genre: "댄스", gender: "남성" },
  { releaseYear: 2007, releaseMonth: 8, title: "거짓말", artist: "BIGBANG", tj: "18530", genre: "댄스", gender: "남성" },
  { releaseYear: 2007, releaseMonth: 9, title: "Tell Me", artist: "원더걸스", tj: "18620", genre: "댄스", gender: "여성" },
  { releaseYear: 2006, releaseMonth: 10, title: "까만안경", artist: "이루", tj: "16470", genre: "발라드", gender: "남성" },
  { releaseYear: 2006, releaseMonth: 4, title: "내 사람", artist: "SG워너비", tj: "15910", genre: "발라드", gender: "남성" },
  { releaseYear: 2005, releaseMonth: 3, title: "겁쟁이", artist: "버즈 (Buzz)", tj: "14680", genre: "록/밴드", gender: "남성" },
  { releaseYear: 2005, releaseMonth: 3, title: "가시", artist: "버즈 (Buzz)", tj: "14750", genre: "록/밴드", gender: "남성" },
  { releaseYear: 2005, releaseMonth: 1, title: "응급실", artist: "izi", tj: "14580", genre: "발라드", gender: "남성" },
  { releaseYear: 2004, releaseMonth: 1, title: "Timeless", artist: "SG워너비", tj: "12680", genre: "발라드", gender: "남성" },
  { releaseYear: 2004, releaseMonth: 10, title: "어머나", artist: "장윤정", tj: "14100", genre: "트로트", gender: "여성" },
  { releaseYear: 2003, releaseMonth: 6, title: "소주 한 잔", artist: "임창정", tj: "10980", genre: "발라드", gender: "남성" },
  { releaseYear: 2003, releaseMonth: 2, title: "체념", artist: "빅마마", tj: "10950", genre: "발라드", gender: "여성" },
  { releaseYear: 2003, releaseMonth: 8, title: "Don't Cry", artist: "더 크로스", tj: "11980", genre: "록/밴드", gender: "남성" },
  { releaseYear: 2002, releaseMonth: 4, title: "No.1", artist: "보아 (BoA)", tj: "9850", genre: "댄스", gender: "여성" },
  { releaseYear: 2002, releaseMonth: 9, title: "낭만고양이", artist: "체리필터", tj: "9980", genre: "록/밴드", gender: "혼성" },
  { releaseYear: 2001, releaseMonth: 6, title: "벌써 일년", artist: "브라운 아이즈", tj: "9510", genre: "발라드", gender: "남성" },
  { releaseYear: 2000, releaseMonth: 8, title: "성인식", artist: "박지윤", tj: "9020", genre: "댄스", gender: "여성" },
  { releaseYear: 2000, releaseMonth: 3, title: "Tears", artist: "소찬휘", tj: "8910", genre: "댄스", gender: "여성" },

  // -----------------------------------------------------------------------
  // --- 1980년 ~ 1999년 실제 발매곡 ---
  // -----------------------------------------------------------------------
  { releaseYear: 1999, releaseMonth: 7, title: "Wa (와)", artist: "이정현", tj: "8450", genre: "댄스", gender: "여성" },
  { releaseYear: 1999, releaseMonth: 8, title: "천년의 사랑", artist: "박완규", tj: "8290", genre: "록/밴드", gender: "남성" },
  { releaseYear: 1999, releaseMonth: 4, title: "이미 슬픈 사랑", artist: "야다", tj: "8390", genre: "록/밴드", gender: "남성" },
  { releaseYear: 1998, releaseMonth: 12, title: "순정", artist: "코요태", tj: "4920", genre: "댄스", gender: "혼성" },
  { releaseYear: 1998, releaseMonth: 9, title: "To Heaven", artist: "조성모", tj: "4680", genre: "발라드", gender: "남성" },
  { releaseYear: 1997, releaseMonth: 7, title: "해변의 여인", artist: "쿨 (COOL)", tj: "4110", genre: "댄스", genre: "혼성" },
  { releaseYear: 1997, releaseMonth: 1, title: "발걸음", artist: "에메랄드 캐슬", tj: "4080", genre: "록/밴드", gender: "남성" },
  { releaseYear: 1996, releaseMonth: 1, title: "인형의 꿈", artist: "일기예보", tj: "3290", genre: "발라드", gender: "남성" },
  { releaseYear: 1995, releaseMonth: 1, title: "잘못된 만남", artist: "김건모", tj: "2420", genre: "댄스", gender: "남성" },
  { releaseYear: 1995, releaseMonth: 1, title: "가질 수 없는 너", artist: "뱅크", tj: "2480", genre: "발라드", gender: "남성" },
  { releaseYear: 1994, releaseMonth: 3, title: "칵테일 사랑", artist: "마로니에", tj: "1980", genre: "댄스", gender: "혼성" },
  { releaseYear: 1994, releaseMonth: 3, title: "기억의 습작", artist: "전람회", tj: "1850", genre: "발라드", gender: "남성" },
  { releaseYear: 1994, releaseMonth: 1, title: "서시", artist: "신성우", tj: "1650", genre: "록/밴드", gender: "남성" },
  { releaseYear: 1992, releaseMonth: 3, title: "난 알아요", artist: "서태지와 아이들", tj: "1210", genre: "댄스", gender: "남성" },
  { releaseYear: 1991, releaseMonth: 9, title: "내 사랑 내 곁에", artist: "김현식", tj: "650", genre: "발라드", gender: "남성" }, // 이미지 속 곡! 1991년 9월 정확매칭!
  { releaseYear: 1990, releaseMonth: 1, title: "She's Gone", artist: "Steelheart", tj: "7120", genre: "록/밴드", gender: "남성" },
  { releaseYear: 1989, releaseMonth: 11, title: "희망사항", artist: "변진섭", tj: "410", genre: "발라드", gender: "남성" },
  { releaseYear: 1988, releaseMonth: 12, title: "그대에게", artist: "무한궤도 (신해철)", tj: "310", genre: "록/밴드", gender: "남성" },
  { releaseYear: 1987, releaseMonth: 8, title: "사랑하기 때문에", artist: "유재하", tj: "250", genre: "발라드", gender: "남성" },
  { releaseYear: 1986, releaseMonth: 12, title: "비처럼 음악처럼", artist: "김현식", tj: "190", genre: "발라드", gender: "남성" },
  { releaseYear: 1985, releaseMonth: 4, title: "바람바람바람", artist: "김범룡", tj: "150", genre: "발라드", gender: "남성" },
  { releaseYear: 1984, releaseMonth: 7, title: "J에게", artist: "이선희", tj: "120", genre: "발라드", gender: "여성" },
  { releaseYear: 1980, releaseMonth: 3, title: "단발머리", artist: "조용필", tj: "50", genre: "댄스", gender: "남성" }
];
